name: Main branch push trigger

on:
    push:
        branches:
            - main

jobs:
    run-on-main:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: running simple command
              run: echo "pushed to main"